### ISSUE TITLE
Out of system memory when unfreeze all of the layers.

### ISSUE THREAD

**Issue by FMsunyh** [qqwweee/keras-yolo3#122]
Hi,
I have a issue when I unfreeze all of the layers. the memory keeps growing.
but the train doesn't start to run. it seen that the train is stopped.
And I try to change a smaller batch size. but it still likes this.

![image](https://user-images.githubusercontent.com/9877644/41640339-ffd84ff4-7493-11e8-8d71-e6bd850bed0b.png)

![image](https://user-images.githubusercontent.com/9877644/41640351-0c9fcb86-7494-11e8-9e77-af962771ea6c.png)

**Comment by dasfaha** [comment]
Same issue.

**Comment by FlyEgle** [comment]
You could use the multi-gpu to train the unfreeze darknet53 model and use the small_batch avoid of OOM

**Comment by FMsunyh** [comment]
* Set load_pretrained=False;
* Use darknet53.weights to fine tuning;
* Change a smaller batch size (batch_size=2);
* Use 2 gpus to train.

I've tried these options. But it still doesn't work when unfreeze all layers.
OOM  is the system memory, not gpu's memory. but my system memory has 32G, I think  that is enough.
Could you give me some ideas? thanks!
@FlyEgle @qqwweee

**Comment by xudezhi123** [comment]
@FMsunyh Could you tell me how to unfreeze all of the layers? I will be appreciate a lot

**Comment by jinxie0731** [comment]
My GPU is NVIDIA GTX 1080Ti(Single), when the batch_size is the origin value(namely 32), I met the same issue, but when I modified it to 10,  train.py could accomplished its work without any error.

**Comment by jinxie0731** [comment]
I think if you want to unfreeze all of the layers, you can try it like this:
when you create the model, you can add this parameter(load_pretrained=False) for the function of create_model():
 model = create_model(input_shape, anchors, num_classes, load_pretrained=False,
            freeze_body=2, weights_path='model_data/yolo_weights.h5')

**Comment by Brizel** [comment]
I set batch_size = 8 & epoch = 20 to solve this problem. Worked on my computer(1080Ti , 32G internal memory).

**Comment by FMsunyh** [comment]
@xudezhi123 
you can check in the train.py, author trains model with frozen layers first, and then continues training with unfreeze all layers.
I hope that can help you.

![image](https://user-images.githubusercontent.com/9877644/41834968-795c5774-7888-11e8-9316-5bab217cb68f.png)

**Comment by FMsunyh** [comment]
@jinxie0731 
Thanks.
I've try this method( set load_pretrained=False ), but same issue with me.

**Comment by sherlockchou86** [comment]
setting smaller batch_size will help

**Comment by xugaoxiang** [comment]
Ubuntu 18.04 64bit, GTX 1070 Ti, 8G, and 32G system memory, training VOC dataset,

1. only train 2 classes, car and person, modify model_data/voc_classes.txt
2 batch_size = 2 & epoch = 20
3 set load_pretrained=False  

After a few minutes, memory hits 100%. Need help.

**Comment by GeHongpeng** [comment]
Update your tensorflow version(1.8.0). It works for me!

**Comment by gittigxuy** [comment]
@xugaoxiang ,请问由于内存溢出而导致中断之后，此时会产生很多临时文件，如何利用这些临时文件继续训练？

**Comment by gittigxuy** [comment]
@sherlockchou86 ,I have set batch_size =1,but it still error:
![default](https://user-images.githubusercontent.com/15090557/42379770-63d78994-815e-11e8-98cf-627d0208c96d.png)
what should I do?

**Comment by gittigxuy** [comment]
@FMsunyh ,have you solved your problem?I encounter same question

**Comment by xugaoxiang** [comment]
@GeHongpeng , Thanks.

Ubuntu 18.04 64bit, GTX 1070 Ti, 8G, and 32G system memory, training VOC dataset
`
only train 2 classes, car and person, modify model_data/voc_classes.txt
batch_size = 2 & epoch = 20
set load_pretrained=False
update tensorflow to 1.8.0
`

The train.py output

`
Epoch 00063: ReduceLROnPlateau reducing learning rate to 9.999999747378752e-06.
Epoch 64/100
1125/1125 [==============================] - 6684s 6s/step - loss: 12.6273 - val_loss: 12.4967
Epoch 65/100
1125/1125 [==============================] - 6686s 6s/step - loss: 12.4838 - val_loss: 12.1972
Epoch 66/100
1125/1125 [==============================] - 6690s 6s/step - loss: 12.1969 - val_loss: 13.0469

Epoch 00066: ReduceLROnPlateau reducing learning rate to 9.999999747378752e-07.
Epoch 67/100
1125/1125 [==============================] - 6687s 6s/step - loss: 12.1996 - val_loss: 12.0781
Epoch 68/100
1125/1125 [==============================] - 6684s 6s/step - loss: 12.3424 - val_loss: 11.9006
Epoch 69/100
1125/1125 [==============================] - 6687s 6s/step - loss: 12.2405 - val_loss: 13.5473
Epoch 70/100
1125/1125 [==============================] - 6690s 6s/step - loss: 12.2212 - val_loss: 10.8682
Epoch 71/100
1125/1125 [==============================] - 6690s 6s/step - loss: 12.3795 - val_loss: 12.4388
Epoch 72/100
1125/1125 [==============================] - 6686s 6s/step - loss: 12.5838 - val_loss: 12.3046
Epoch 73/100
1125/1125 [==============================] - 6688s 6s/step - loss: 12.3020 - val_loss: 11.7841
Epoch 74/100
1125/1125 [==============================] - 6692s 6s/step - loss: 12.2491 - val_loss: 11.7993

Epoch 00074: ReduceLROnPlateau reducing learning rate to 9.999999974752428e-08.
Epoch 75/100
1125/1125 [==============================] - 6694s 6s/step - loss: 12.1978 - val_loss: 12.5842
Epoch 76/100
1125/1125 [==============================] - 6694s 6s/step - loss: 12.3493 - val_loss: 12.2501
Epoch 77/100
1125/1125 [==============================] - 6693s 6s/step - loss: 12.4197 - val_loss: 11.5807

Epoch 00077: ReduceLROnPlateau reducing learning rate to 1.0000000116860975e-08.
Epoch 78/100
1125/1125 [==============================] - 6686s 6s/step - loss: 12.1625 - val_loss: 11.9507
Epoch 79/100
1125/1125 [==============================] - 6694s 6s/step - loss: 12.0322 - val_loss: 11.9005
Epoch 80/100
1125/1125 [==============================] - 6694s 6s/step - loss: 12.4152 - val_loss: 13.1308

Epoch 00080: ReduceLROnPlateau reducing learning rate to 9.999999939225292e-10.
Epoch 00080: early stopping
`
It seems that something is wrong, but logs/115/trained_weights_final.h5 is generated successfully.I use the trained file to test an image using yolo.py(ue the same class file and anchor file as train.py), but NO box was found.

**Comment by GeHongpeng** [comment]
@xugaoxiang No problem!
If I got it right, maybe you use the convert script in a wrong way.
darknet53.cfg just has only convolutional layers, so the converted weight did not  contain any yolo layers.

I trained the VOC dataset  under Ubuntu 16.04 64bit, V100 16G, and 32G system memory.
The difference between darknet and keras is still there, but it can detect most of the objects.

COCO dataset may be better.

**Comment by GeHongpeng** [comment]
@gittigxuy 你所说的临时文件都指哪些文件？

**Comment by xugaoxiang** [comment]
@GeHongpeng , and how to use the convert.py? Or should I use the trained_weights_final.h5 directly in yolo.py??

**Comment by GeHongpeng** [comment]
@xugaoxiang
You can use the weight directly in the keras framework, you do not need to convert it.
Because it was trained under keras framework.

**Comment by xugaoxiang** [comment]
@GeHongpeng , thank you.

I keep two classes in voc_classes.txt (car and person, same as classes in voc_annotation.py),  but **NO** box was found using the trained_weights_final.h5. Why?

`(yolo) longjing@FR:~/Work/yolo3/keras-yolo3$ python yolo.py 
Using TensorFlow backend.
2018-07-10 09:58:21.344637: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
logs/115/trained_weights_final.h5 model, anchors, and classes loaded.
Input image filename:test_image/3.jpeg
(416, 416, 3)
Found 0 boxes for img
1.944707546965219
Input image filename:../darknet/data/person.jpg
(416, 416, 3)
Found 0 boxes for img
0.9323207149282098
`

**Comment by GeHongpeng** [comment]
@xugaoxiang 
How about the "score" parameter in the YOLOPredictor?
You can set it to a low value such as 0.1 or lower, check the result.

If still no box was found, maybe your training was not enough or something wrong in the training.

I will do the same training later, and share the result.

**Comment by xugaoxiang** [comment]
@GeHongpeng , default score is 0.3. Same result when score is set to 0.1 and 0.01. Looking forward to your result.

**Comment by GeHongpeng** [comment]
@xugaoxiang  
I started the training, the loss is dramatically dropping below 5.0. 
It is still dropping.
I use the darknet53(freezing the backbone) to warm up for 50 epochs, then unfreeze all of the layers for further training.
I will share the result when the training is done.

```
Epoch 15/50

  1/155 [..............................] - ETA: 4:21 - loss: 4.7309
  2/155 [..............................] - ETA: 4:19 - loss: 4.7433
  3/155 [..............................] - ETA: 4:18 - loss: 4.7399
  4/155 [..............................] - ETA: 4:16 - loss: 4.7395
  5/155 [..............................] - ETA: 4:14 - loss: 4.7379
  6/155 [>.............................] - ETA: 4:13 - loss: 4.7377
  7/155 [>.............................] - ETA: 4:11 - loss: 4.7358
  8/155 [>.............................] - ETA: 4:09 - loss: 4.7358
  9/155 [>.............................] - ETA: 4:08 - loss: 4.7367
 10/155 [>.............................] - ETA: 4:06 - loss: 4.7373
 11/155 [=>............................] - ETA: 4:04 - loss: 4.7361
 12/155 [=>............................] - ETA: 4:02 - loss: 4.7348
 13/155 [=>............................] - ETA: 4:01 - loss: 4.7350
 14/155 [=>............................] - ETA: 3:59 - loss: 4.7341
 15/155 [=>............................] - ETA: 3:57 - loss: 4.7335
 16/155 [==>...........................] - ETA: 3:56 - loss: 4.7330
 17/155 [==>...........................] - ETA: 3:55 - loss: 4.7323
 18/155 [==>...........................] - ETA: 3:55 - loss: 4.7316
 19/155 [==>...........................] - ETA: 3:55 - loss: 4.7308
 20/155 [==>...........................] - ETA: 3:54 - loss: 4.7305
 21/155 [===>..........................] - ETA: 3:54 - loss: 4.7302
 22/155 [===>..........................] - ETA: 3:53 - loss: 4.7295
 23/155 [===>..........................] - ETA: 3:53 - loss: 4.7295
 24/155 [===>..........................] - ETA: 3:52 - loss: 4.7288
 25/155 [===>..........................] - ETA: 3:50 - loss: 4.7289
 26/155 [====>.........................] - ETA: 3:49 - loss: 4.7280
 27/155 [====>.........................] - ETA: 3:48 - loss: 4.7274
 28/155 [====>.........................] - ETA: 3:47 - loss: 4.7267
 29/155 [====>.........................] - ETA: 3:46 - loss: 4.7260
 30/155 [====>.........................] - ETA: 3:45 - loss: 4.7256
 31/155 [=====>........................] - ETA: 3:44 - loss: 4.7256
 32/155 [=====>........................] - ETA: 3:42 - loss: 4.7252
 33/155 [=====>........................] - ETA: 3:41 - loss: 4.7248
 34/155 [=====>........................] - ETA: 3:40 - loss: 4.7245
 35/155 [=====>........................] - ETA: 3:38 - loss: 4.7241
 36/155 [=====>........................] - ETA: 3:37 - loss: 4.7239
 37/155 [======>.......................] - ETA: 3:36 - loss: 4.7234
 38/155 [======>.......................] - ETA: 3:34 - loss: 4.7238
 39/155 [======>.......................] - ETA: 3:32 - loss: 4.7231
```

**Comment by GeHongpeng** [comment]
@xugaoxiang 
I have been training voc dataset for about 45 epochs(use darknet53 weight, freeze only the backbone), the loss now is dropping below 10.(your loss seems not good)

After training 50 epochs, I will unfreeze all the layer for further training.
I will report the result later.

**Comment by GeHongpeng** [comment]
@xugaoxiang 
Hi, My training loss is still dropping. I tested the current weight, here is the result.
Not so good, but it can detect the car and the peroson.

![voc_car person1](https://user-images.githubusercontent.com/16913359/42544498-2cb21064-84ed-11e8-81c2-dc3998a5b8a4.png)
![voc_car person2](https://user-images.githubusercontent.com/16913359/42544506-34bf0bf4-84ed-11e8-8e1e-1e9b3faf3c23.png)

**Comment by xugaoxiang** [comment]
@GeHongpeng , Great job, thanks, I'll do the training again.

**Comment by GeHongpeng** [comment]
@xugaoxiang 
If you have any questions, please let me know!

**Comment by xugaoxiang** [comment]
@GeHongpeng , Now , I use the darknet command line to train weigts on VOC dataset, and then convert the weights file to .h5 file. It's OK.

**Comment by Brizel** [comment]
@GeHongpeng 

Could you tell me your computer configuration ?
My GPU memery is 12G, and I can only set batch_size = 8 to train VOC dataset. After 43 epochs, the final loss is 15.3.

**Comment by QuntuamLoop** [comment]
thank your shareing, maybe I should ask my boss to update the 1070 card

________________________________
发件人: GeHongpeng <notifications@github.com>
发送时间: 2018年7月18日 11:25
收件人: qqwweee/keras-yolo3
抄送: QuntuamLoop; Mention
主题: Re: [qqwweee/keras-yolo3] Out of system memory when unfreeze all of the layers. (#122)


@QuntuamLoop<https://github.com/QuntuamLoop>

  1.  Use darknet53 weight, freeze only the backbone, batch_size=32, Adam(lr=1e-3), Epochs=50
  2.  Unfreeze all layers, batch_size=16(it depends your GPU momery), Adam(lr=1e-4), Epochs=30
  3.  Unfreeze all layers, batch_size=16(it depends your GPU momery), SGD(lr=0.003, decay=1e-6, momentum=0.9, nesterov=True, clipnorm=5), Epochs=60

If needed, you can do further training. Such as changing the batch to 8 or 4, changing the SGD learning rate to 0.0003 or 0.00003.

―

**Comment by Samonsix** [comment]
my tensorflow-gpu==1.5.0
GPU: Tesla P100, Mem：16G
System memory:20G
has the same question: after i unfreeze all layers, my process killed by system because of out of memory.
when i update tensorflow-gpu==1.9.0, it's ok!

**Comment by ss199302** [comment]
@GeHongpeng  Hello！Did you modify the training method? Did it work better?
Use darknet53 weight, freeze only the backbone, batch_size=32, Adam(lr=1e-3), Epochs=50
Unfreeze all layers, batch_size=16(it depends your GPU momery), Adam(lr=1e-4), Epochs=30
Unfreeze all layers, batch_size=16(it depends your GPU momery), SGD(lr=0.003, decay=1e-6, momentum=0.9, nesterov=True, clipnorm=5), Epochs=60

**Comment by fourth-archive** [comment]
@FMsunyh @dasfaha @xugaoxiang @FlyEgle @xudezhi123 this YOLOv3 tutorial may help you: 
https://github.com/ultralytics/yolov3/wiki/Train-Custom-Data

The accompanying repository works on MacOS, Windows and Linux, includes multigpu and multithreading, performs inference on images, videos, webcams, and an iOS app. It also tests to slightly higher mAPs than darknet, including on the latest `YOLOv3-SPP.weights` (**60.7 COCO mAP**), and offers the ability to train custom datasets from scratch to darknet performance, all using PyTorch :)
https://github.com/ultralytics/yolov3

<table style="width:100%">
  <tr><th><img src="https://user-images.githubusercontent.com/26833433/54523854-227d0580-4979-11e9-9801-26a3be239875.jpg" width="300"></th>
    <th><img src="https://storage.googleapis.com/ultralytics/logo/logoname1000.png" width="140">
  <br><br/>
  <p> <a href="https://itunes.apple.com/app/id1452689527">
  <img href="https://itunes.apple.com/app/id1452689527" src="https://user-images.githubusercontent.com/26833433/50044365-9b22ac00-0082-11e9-862f-e77aee7aa7b0.png" width="160"> 
  </a> </p></th> 
  </tr>
</table>

**Comment by Emma0928** [comment]
![1559140429(1)](https://user-images.githubusercontent.com/40055478/58565773-e52ed100-8261-11e9-93d3-0e1eb4c4f519.jpg)
I want to know why my progress directly skips the unfreeze stage.

**Comment by remcova** [comment]
> ![1559140429(1)](https://user-images.githubusercontent.com/40055478/58565773-e52ed100-8261-11e9-93d3-0e1eb4c4f519.jpg)
> I want to know why my progress directly skips the unfreeze stage.

How did you get the metric val_loss working? Could you show a code example? 
I've tried several times to get the validation loss but unfortunately without any results.
